/*
 * generated by Xtext 2.27.0
 */
package org.eclipse.daanse.mdx.xtext.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.daanse.mdx.xtext.mdx.MdxPackage;
import org.eclipse.daanse.mdx.xtext.mdx.SelectStatement;
import org.eclipse.daanse.mdx.xtext.services.MdxGrammarAccess;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;

@SuppressWarnings("all")
public class MdxSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private MdxGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == MdxPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case MdxPackage.SELECT_STATEMENT:
				sequence_SelectStatement(context, (SelectStatement) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * <pre>
	 * Contexts:
	 *     MdxStatement returns SelectStatement
	 *     SelectStatement returns SelectStatement
	 *
	 * Constraint:
	 *     {SelectStatement}
	 * </pre>
	 */
	protected void sequence_SelectStatement(ISerializationContext context, SelectStatement semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
