/*
 * generated by Xtext 2.27.0
 */
package org.eclipse.daanse.mdx.xtext;

/**
 * Initialization support for running Xtext languages without Equinox extension
 * registry.
 */
public class MdxStandaloneSetup extends MdxStandaloneSetupGenerated {

  public static void doSetup() {
    new MdxStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
