/*
 * generated by Xtext 2.27.0
 */
package org.eclipse.daanse.mdx.xtext.formatting2;

import org.eclipse.xtext.formatting2.AbstractJavaFormatter;

public class MdxFormatter extends AbstractJavaFormatter {
	
	
	
}
