/*
 * generated by Xtext 2.28.0
 */
package org.eclipse.daanse.mdx.xtext.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.daanse.mdx.xtext.parser.antlr.internal.InternalMdxParser;
import org.eclipse.daanse.mdx.xtext.services.MdxGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class MdxParser extends AbstractAntlrParser {

	@Inject
	private MdxGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalMdxParser createParser(XtextTokenStream stream) {
		return new InternalMdxParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "MdxStatement";
	}

	public MdxGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MdxGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
