/**
 * generated by Xtext 2.28.0
 */
package org.eclipse.daanse.mdx.xtext.mdx;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc --> The <b>Factory</b> for the model. It provides a
 * create method for each non-abstract class of the model. <!-- end-user-doc -->
 * 
 * @see org.eclipse.daanse.mdx.xtext.mdx.MdxPackage
 * @generated
 */
public interface MdxFactory extends EFactory {
  /**
   * The singleton instance of the factory. <!-- begin-user-doc --> <!--
   * end-user-doc -->
   * 
   * @generated
   */
  MdxFactory eINSTANCE = org.eclipse.daanse.mdx.xtext.mdx.impl.MdxFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Statement</em>'. <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * 
   * @return a new object of class '<em>Statement</em>'.
   * @generated
   */
  MdxStatement createMdxStatement();

  /**
   * Returns a new object of class '<em>Select Statement</em>'. <!--
   * begin-user-doc --> <!-- end-user-doc -->
   * 
   * @return a new object of class '<em>Select Statement</em>'.
   * @generated
   */
  SelectStatement createSelectStatement();

  /**
   * Returns the package supported by this factory. <!-- begin-user-doc --> <!--
   * end-user-doc -->
   * 
   * @return the package supported by this factory.
   * @generated
   */
  MdxPackage getMdxPackage();

} // MdxFactory
