/**
 * generated by Xtext 2.28.0
 */
package org.eclipse.daanse.mdx.xtext.mdx;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Select Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.eclipse.daanse.mdx.xtext.mdx.MdxPackage#getSelectStatement()
 * @model
 * @generated
 */
public interface SelectStatement extends EObject
{
} // SelectStatement
