/*
 * generated by Xtext 2.28.0
 */
package org.eclipse.daanse.mdx.xtext.validation;

import org.eclipse.xtext.preferences.PreferenceKey;
import org.eclipse.xtext.util.IAcceptor;
import org.eclipse.xtext.validation.ConfigurableIssueCodesProvider;
import org.eclipse.xtext.validation.SeverityConverter;

public class MdxConfigurableIssueCodesProvider extends ConfigurableIssueCodesProvider {
  protected static final String ISSUE_CODE_PREFIX = "org.eclipse.daanse.mdx.xtext.";

  public static final String DEPRECATED_MODEL_PART = ISSUE_CODE_PREFIX + "deprecatedModelPart";

  @Override
  protected void initialize(IAcceptor<PreferenceKey> acceptor) {
    super.initialize(acceptor);
    acceptor.accept(create(DEPRECATED_MODEL_PART, SeverityConverter.SEVERITY_WARNING));
  }
}
