/*
 * generated by Xtext 2.28.0
 */
package org.eclipse.daanse.mdx.xtext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMdxScopeProvider extends DelegatingScopeProvider {
}
