
package org.eclipse.daanse.xmla_ws;

import jakarta.jws.WebService;
import jakarta.xml.ws.BindingType;
import jakarta.xml.ws.Holder;
import org.eclipse.daanse.xmla.model.jaxb.xmla.BeginSession;
import org.eclipse.daanse.xmla.model.jaxb.xmla.Discover;
import org.eclipse.daanse.xmla.model.jaxb.xmla.DiscoverResponse;
import org.eclipse.daanse.xmla.model.jaxb.xmla.EndSession;
import org.eclipse.daanse.xmla.model.jaxb.xmla.Execute;
import org.eclipse.daanse.xmla.model.jaxb.xmla.ExecuteResponse;
import org.eclipse.daanse.xmla.model.jaxb.xmla.Session;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 4.0.0-M3
 * Generated source version: 3.0
 * 
 */
@WebService(portName = "MsXmlAnalysisSoapPort", serviceName = "MsXmlAnalysisService", targetNamespace = "urn:daanse-eclipse-org:xmla-ws", wsdlLocation = "file:/home/stbischof/dev/git/org.eclipse.daanse.xmla/org.eclipse.daanse.xmla.definition/xmla.wsdl", endpointInterface = "org.eclipse.daanse.xmla_ws.MsXmlAnalysisSoapPortType")
@BindingType("http://schemas.xmlsoap.org/wsdl/soap/http")
public class MsXmlAnalysisService_MsXmlAnalysisSoapPortImpl
    implements MsXmlAnalysisSoapPortType
{


    public MsXmlAnalysisService_MsXmlAnalysisSoapPortImpl() {
    }

    /**
     * 
     * @param sspiHandshake
     * @return
     *     returns org.eclipse.daanse.xmla.model.jaxb.ext.AuthenticateResponse.Return
     */
    public org.eclipse.daanse.xmla.model.jaxb.ext.AuthenticateResponse.Return authenticate(byte[] sspiHandshake) {
        //replace with your impl here
        return null;
    }

    /**
     * 
     * @param endSession
     * @param session
     * @param beginSession
     * @param parameters
     * @return
     *     returns org.eclipse.daanse.xmla.model.jaxb.xmla.DiscoverResponse
     */
    public DiscoverResponse discover(Discover parameters, Holder<Session> session, BeginSession beginSession, EndSession endSession) {
        //replace with your impl here
        return null;
    }

    /**
     * 
     * @param endSession
     * @param session
     * @param beginSession
     * @param parameters
     * @return
     *     returns org.eclipse.daanse.xmla.model.jaxb.xmla.ExecuteResponse
     */
    public ExecuteResponse execute(Execute parameters, Holder<Session> session, BeginSession beginSession, EndSession endSession) {
        //replace with your impl here
        return null;
    }

}
