/**
 * generated by Xtext 2.27.0
 */
package org.eclipse.daanse.mdx.xtext.mdx.impl;

import org.eclipse.daanse.mdx.xtext.mdx.MdxPackage;
import org.eclipse.daanse.mdx.xtext.mdx.SelectStatement;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Select Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class SelectStatementImpl extends MdxStatementImpl implements SelectStatement
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SelectStatementImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MdxPackage.Literals.SELECT_STATEMENT;
  }

} //SelectStatementImpl
