/*
 * generated by Xtext 2.27.0
 */
package org.eclipse.daanse.mdx.xtext.web;


/**
 * Use this class to register additional components to be used within the web application.
 */
public class MdxWebModule extends AbstractMdxWebModule {
}
