/*
 * generated by Xtext 2.27.0
 */
package org.eclipse.daanse.mdx.xtext.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class MdxAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/eclipse/daanse/mdx/xtext/parser/antlr/internal/InternalMdxParser.tokens");
	}
}
