/*
 * generated by Xtext 2.27.0
 */
package org.eclipse.daanse.mdx.xtext.web;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link MdxWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractMdxWebModule extends DefaultWebModule {

}
