name: CI Build

on:
  push:
    branches-ignore:
    - 'dependabot/**'
    paths-ignore:
    - '.github/**/*codeql*'
    - '.github/*.yml'
  pull_request:
    paths-ignore:
    - '.github/**/*codeql*'
    - '.github/*.yml'

env:
  LC_ALL: en_US.UTF-8
  MAVEN_OPTS: >-
    -Dhttp.keepAlive=false
    -Dmaven.wagon.http.pool=false
    -Dmaven.wagon.http.retryHandler.count=3

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        java:
        - '11'
        - '17'
        - '18'
        os:
        - 'ubuntu-latest'
        include:
        - os: 'windows-latest'
          java: '17'
        - os: 'ubuntu-latest'
          java: '17'
          canonical: ${{ (github.repository == 'xmla-services/org.eclipse.daanse.xmla') && ((github.ref == 'refs/heads/main') || (github.ref == 'refs/heads/release')) && (github.event_name != 'pull_request') }}
        - os: 'ubuntu-latest'
          java: '17'
          experimental: true
          mavenopts: '-Pbnd-next'
    name: JDK${{ matrix.java }} ${{ matrix.os }} ${{ matrix.mavenopts }}
    runs-on: ${{ matrix.os }}
    steps:
    - name: Git Checkout
      uses: actions/checkout@v4
    - name: Set up Java ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
    - name: Build
      id: build
      continue-on-error: ${{ matrix.experimental }}
      run: |
        ./.github/scripts/build.sh ${{ matrix.mavenopts }}
    - name: Configure settings.xml for Publish
      if: ${{ matrix.canonical }}
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
        server-id: ossrh
        server-username: OSSRH_USERNAME
        server-password: OSSRH_PASSWORD
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
        gpg-passphrase: GPG_PASSPHRASE
    - name: Publish
      if: ${{ matrix.canonical }}
      run: |
        ./.github/scripts/publish.sh -Possrh
      env:
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
